import Btn from "@/app/shared/ui/btn/btn";
import Title from "@/app/shared/ui/title/title";
import PaginationRow from "@/app/shared/ui/paginationRow/paginationRow";
import LeftScale from "@/app/shared/ui/leftScale/leftScale";
import Iframe from "@/app/shared/ui/Iframe/Iframe";
import BtnSlider from "@/app/shared/ui/btnSlider/btnSlider";
export {Btn as Btn}
export {Title as Title}
export {PaginationRow as PaginationRow}
export {LeftScale as LeftScale}
export {Iframe as Iframe}
export {BtnSlider as BtnSlider}