import Btn from "./ui/btn/btn";
import Title from "./ui/title/title";
import PaginationRow from "./ui/paginationRow/paginationRow";
import LeftScale from "./ui/leftScale/leftScale";
import Iframe from "./ui/Iframe/Iframe";
import BtnSlider from "./ui/btnSlider/btnSlider";
export {Btn as Btn}
export {Title as Title}
export {PaginationRow as PaginationRow}
export {LeftScale as LeftScale}
export {Iframe as Iframe}
export {BtnSlider as BtnSlider}